version: '3.5'

services:
  redis:
    container_name: 'parallel_redis'
    image: redis
    ports:
      - 6379:6379

  worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - .:/app
    command: >
      bash -c 'python start_celery.py && celery -A app.celery worker --queues=configs --loglevel=info'
    depends_on:
      - redis
